# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class FilePageUi(object):
    def setupUi(self, Ui):
        Ui.setObjectName("Ui")
        Ui.resize(492, 456)
        self.verticalLayout = QtWidgets.QVBoxLayout(Ui)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dir = BreadcrumbBar(Ui)
        self.dir.setObjectName("dir")
        self.verticalLayout.addWidget(self.dir)
        self.ScrollArea = ScrollArea(Ui)
        self.ScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ScrollArea.setWidgetResizable(True)
        self.ScrollArea.setObjectName("ScrollArea")
        self.box = QtWidgets.QWidget()
        self.box.setGeometry(QtCore.QRect(0, 0, 474, 413))
        self.box.setObjectName("box")
        self.ScrollArea.setWidget(self.box)
        self.verticalLayout.addWidget(self.ScrollArea)

        self.retranslateUi(Ui)
        QtCore.QMetaObject.connectSlotsByName(Ui)

    def retranslateUi(self, Ui):
        _translate = QtCore.QCoreApplication.translate
        Ui.setWindowTitle(_translate("Ui", "Form"))
from qfluentwidgets import BreadcrumbBar, ScrollArea
