# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UpDownItem(object):
    def setupUi(self, Ui):
        Ui.setObjectName("Ui")
        Ui.resize(556, 68)
        Ui.setMinimumSize(QtCore.QSize(0, 68))
        Ui.setMaximumSize(QtCore.QSize(16777215, 68))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Ui)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.info = QtWidgets.QLabel(Ui)
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 2, 0, 1, 1)
        self.name = QtWidgets.QLabel(Ui)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 0, 1, 1)
        self.progres_text = QtWidgets.QLabel(Ui)
        self.progres_text.setText("")
        self.progres_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progres_text.setObjectName("progres_text")
        self.gridLayout.addWidget(self.progres_text, 2, 1, 1, 1)
        self.progress = ProgressBar(Ui)
        self.progress.setObjectName("progress")
        self.gridLayout.addWidget(self.progress, 1, 0, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.start_btn = ToolButton(Ui)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_2.addWidget(self.start_btn)
        self.stop_btn = ToolButton(Ui)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_2.addWidget(self.stop_btn)
        self.re_btn = ToolButton(Ui)
        self.re_btn.setObjectName("re_btn")
        self.horizontalLayout_2.addWidget(self.re_btn)
        self.close_btn = TransparentToolButton(Ui)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_2.addWidget(self.close_btn)

        self.retranslateUi(Ui)
        QtCore.QMetaObject.connectSlotsByName(Ui)

    def retranslateUi(self, Ui):
        _translate = QtCore.QCoreApplication.translate
        Ui.setWindowTitle(_translate("Ui", "Form"))
        self.info.setText(_translate("Ui", "未开始"))
        self.name.setText(_translate("Ui", "name"))
from qfluentwidgets import ProgressBar, ToolButton, TransparentToolButton
